apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: app
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env
          image: smimages2025/url-shortener:latest
          name: app
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
