services:
  app:
    image: smimages2025/url-shortener:latest
    ports:
      - "3000:3000"
    env_file: ".env"
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine
    container_name: url-shortener-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: