apiVersion: v1
kind: Service
metadata:
  name: node-typescript-k8s-app
  labels:
    app: node-typescript-k8s-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: node-typescript-k8s-app